feat: introduce admin apps page
automatisch/automatisch pull request #1296
Opened 2023-09-22 08:24 UTC by kattoczko

[AUT-257](https://linear.app/automatisch/issue/AUT-257/create-a-sidebar-link-on-admin-settings)  [AUT-258](https://linear.app/automatisch/issue/AUT-258/create-a-page-for-admin-settingsapps)

Currently connections count and flow count returned from getApps are empty. It should be like this for now, right?
I didn't know if I should set any restrictions for accessing /admin-settings/apps page, so if there should be any let me know.

2023-09-29 15:41 UTC, barinali commented
@kattoczko the current `count`s for flows and connections are fine. They'll be addressed later, possibly in the shared connection pull request (#1272).

2023-09-29 15:57 UTC, barinali requested changes

2023-10-04 12:26 UTC, kattoczko commented on packages/web/src/components/AdminSettingsLayout/index.tsx
> +    {
I added the permission check.

2023-10-05 07:53 UTC, barinali approved these changes

2023-10-05 07:54 UTC, merged