feat(notion): add update database item action
automatisch/automatisch pull request #1459
Opened 2023-11-30 15:13 UTC by ridvanakca

resolves #1420

2023-12-18 14:58 UTC, barinali requested changes

2023-12-18 14:58 UTC, barinali commented on packages/backend/src/apps/notion/dynamic-data/list-database-items/index.ts
> +          name: database.properties.Name.title[0].plain_text,
This throws an unexpected error as there may be entries without any "title" set.

2025-07-09 13:49 UTC, barinali approved these changes

2025-07-10 23:16 UTC, kuba618 approved these changes

2025-07-16 16:42 UTC, merged