refacor: implement rest API endpoint for get app and get apps
automatisch/automatisch pull request #1696
Opened 2024-03-06 11:47 UTC by ridvanakca

2024-03-11 12:07 UTC, barinali requested changes

2024-03-11 14:24 UTC, barinali approved these changes

2024-03-11 14:26 UTC, merged

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useActionSubsteps.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useActions.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useAdminAppAuthClient.ee.js
>      queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useApp.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useAppAuth.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useApps.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useLazyApps.js
> +    mutationFn: async ({ payload }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useTriggerSubsteps.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed

2024-03-13 13:39 UTC, kattoczko commented on packages/web/src/hooks/useTriggers.js
> +    queryFn: async ({ payload, signal }) => {
payload is not used and could be removed