refactor: rewrite useFlows as useConnectionFlows and useAppFlows with RQ
automatisch/automatisch pull request #1746
Opened 2024-03-19 15:55 UTC by ridvanakca

2024-03-19 16:26 UTC, barinali requested changes

2024-03-19 16:26 UTC, barinali commented on packages/web/src/components/AppFlows/index.jsx
> +  const flows = connectionFlows?.data?.data || appFlows?.data?.data || [];
Let's depend on `isConnectionFlowEnabled` instead of data's existence. The same for the `pageInfo`.

2024-03-20 14:13 UTC, barinali approved these changes

2024-03-20 14:13 UTC, merged

2024-03-21 08:31 UTC, kattoczko reviewed
Looks good to me.