refactor: rewrite useBillingAndUsageData with useSubscription and useUserTrial
automatisch/automatisch pull request #1780
Opened 2024-03-28 13:15 UTC by ridvanakca

2024-03-28 17:37 UTC, barinali requested changes

2024-03-28 17:37 UTC, barinali commented on packages/backend/src/graphql/schema.graphql
>  type MonthlyQuota {
We should remove other types that are only used with `Subscription` as well, like MonthlyQuota, NextBIllAmount etc.

2024-04-03 13:44 UTC, kattoczko requested changes
In the Paddle.ee.jsx file the old graphql queries are used:

line: 32
```
await apolloClient.refetchQueries({
      include: ['GetTrialStatus', 'GetBillingAndUsage'],
 });
```

2024-04-03 13:44 UTC, kattoczko commented on packages/web/src/hooks/useSubscription.ee.js
> +    [checkoutCompleted, hasSubscription],
This two useEffects could be limited to just one. For example: 

`if (checkoutCompleted) {
        setIsPolling(!hasSubscription);
  }`

2024-04-05 12:14 UTC, kattoczko approved these changes

2024-04-08 12:43 UTC, barinali requested changes

2024-04-08 12:43 UTC, barinali commented on packages/web/src/components/UsageDataInformation/index.ee.jsx
> +        action: '/settings/billing/upgrade',
`URLS.SETTINGS_PLAN_UPGRADE` should be used here.

2024-04-08 13:22 UTC, barinali approved these changes

2024-04-08 13:22 UTC, merged