feat(todoist): add app, authentication, docs
automatisch/automatisch pull request #826
Opened 2023-01-04 17:19 UTC by irlevesque

Hi, this PR adds support for triggering on Todoist tasks and for creating new tasks as an action. There were some lint errors but they look to be unrelated to my changes.

2023-01-06 15:59 UTC, barinali commented
Hey @irlevesque, 

Thanks for your first contribution to Automatisch! 🎉 I have already started reviewing this pull request. However, I'm not done with it, as it takes time and effort. Nevertheless, I'll submit my review as much as I have now and continue reviewing.

2023-01-06 16:03 UTC, barinali requested changes
@irlevesque, thanks once again! I've reviewed everything besides the trigger you prepared. I'll submit another review for that part once I conclude it.

Let me know if you're cool with me pushing changes to your branch for any remarks I have made*, as I'd like to support you here.

\* I have tried to provide suggestions for the remarks. I hope it eases the review on your end.

2023-01-06 16:13 UTC, barinali commented on packages/backend/src/apps/todoist/triggers/get-tasks/get-tasks.ts
> +  requestPath += '&label=' + ($.step.parameters.label as string).trim();
@irlevesque, I could not manage to get tasks by "label". I provided `label name` as a value (I even tried it surrounded with quotes) and tested it. However, it doesn't give an active task with the label even though I see such tasks in the API response when I do not try to filter it by `label`.

I wonder if you could help me with testing this.

2023-01-06 16:53 UTC, barinali commented on packages/backend/src/apps/todoist/triggers/get-tasks/get-tasks.ts
> +  requestPath += '&label=' + ($.step.parameters.label as string).trim();
I see that I was using something called "shared label" and it wasn't working. Now, I tried it with a personal label and it filters by `label`! I am fine to resolve this conversation upon this.

2023-01-06 18:36 UTC, barinali commented
@irlevesque, I am done with the review. I'd like to ask if you'd be up to reworking the authentication with [OAuth2 protocol](https://developer.todoist.com/guides/#oauth). I'd also be happy to provide this branch with that rework.

2023-01-07 04:21 UTC, irlevesque commented on packages/backend/src/apps/todoist/actions/create-task/index.ts
> +    },
Nice, I didn't realize this was possible. One thing that would be nice would be to regenerate the dynamic data based on other form fields -- for example, when a project is selected, the project ID could be used to generate a list of section IDs for that specific project.

2023-01-07 04:22 UTC, irlevesque commented on packages/backend/src/apps/todoist/triggers/get-tasks/get-tasks.ts
> +  const response = await $.http.get(requestPath);
OK, updated. I noticed that with `params` the `trim()` would throw an error if the parameter wasn't set. I'm not sure how safe it is to remove `trim()` but that was the only way I could find to cleanly allow the parameters to be optional.

2023-01-07 04:27 UTC, irlevesque commented
Hi @barinali -- great feedback, thanks! Please see my comments above and let me know if there should be any more changes. I can take a look into the OAuth2 requirements as time allows, but perhaps that can be in a follow-up PR?

2023-01-07 10:50 UTC, barinali commented on packages/backend/src/apps/todoist/actions/create-task/index.ts
> +    },
It's already feasible. The global variable (`$`) in the dynamic data implementation can access its step parameters as can be seen at [GitHub - list a repository labels](https://github.com/automatisch/automatisch/blob/main/packages/backend/src/apps/github/dynamic-data/list-labels/index.ts#L16) sample. In the Todoist case, you should be able to access the project ID in the same approach. Automatisch will also show an error if the `projectId` field is empty when you define a `dependsOn` option in the `sectionId` field to imply `sectionId` field relies on the `projectId` field.

\- `dependsOn` definition sample; https://github.com/automatisch/automatisch/blob/main/packages/backend/src/apps/github/triggers/new-issues/index.ts#L65
\- A sample for defining a source to fetch dynamic data for the dropdown, https://github.com/automatisch/automatisch/blob/main/packages/backend/src/apps/github/triggers/new-issues/index.ts#L66-L79. In this sample, you'll see we send `parameters.repo` as an argument to make it available in the dynamic data implementation.

We can also bring this in a separate pull request later. I can also take care of this if you let me know if it's fine.

2023-01-07 10:58 UTC, barinali commented on packages/backend/src/apps/todoist/triggers/get-tasks/get-tasks.ts
> +  const response = await $.http.get(requestPath);
We may use conditional chaining as in `($.step.parameters.filter as string)?.trim()`, which should trim defined and should not throw when it's `null`. What do you think?

2023-01-07 11:02 UTC, barinali commented
> Hi @barinali -- great feedback, thanks! Please see my comments above and let me know if there should be any more changes. I can take a look into the OAuth2 requirements as time allows, but perhaps that can be in a follow-up PR?

Thanks a lot for the quick iteration of the remarks! I appreciate it. Once we conclude the new comments I wrote, I'd be happy to proceed with this branch.

Regarding the OAuth2, as you mentioned, we could do it in a separate pull request. I can also take care of that. Let me know how you'd prefer it.

2023-01-07 13:44 UTC, irlevesque commented on packages/backend/src/apps/todoist/actions/create-task/index.ts
> +    },
Thanks, that works perfectly.

2023-01-07 13:48 UTC, irlevesque commented
Thanks again for the helpful feedback, which I've incorporated into this branch. 

> Regarding the OAuth2, as you mentioned, we could do it in a separate pull request. I can also take care of that. Let me know how you'd prefer it.

Sure, if you'd like to handle that, that would be great. My needs are met with a simple API token.

2023-01-07 14:09 UTC, barinali approved these changes
@irlevesque, I appreciate your contribution to Automatisch! Thanks a bunch.

As discussed, I'll rework the authentication with OAuth 2 later. At that point, you might need to "reconnect" your connection for Todoist, depending on how the migration works.

2023-01-07 14:09 UTC, merged